insert into dbkpop.Song(albumName,duration,songName) VALUES

('Be',207,'Life Goes On'),
('Be',222,'Fly to My Room'),
('Be',255,'Blue & Grey'),
('Be',180,'Skit'),
('Be',202,'Telepathy'),
('Be',240,'Dis-ease'),
('Be',205,'Stay'),
('Butter',164,'Butter'),
('Dynamite',199,'Dynamite'),
('Not Shy',204,'Not Shy'),
('Not Shy',202,'Dont give a what'),
('Not Shy',215,'Louder'),
('Not Shy',200,'iD'),
('Not Shy',212,'Surf'),
('Not Shy',240,'Be in Love'),
('Border: Day One',109,'Intro: Walk the line'),
('Border: Day One',183,'Given-Taken'),
('Border: Day One',190,'Let me in'),
('Border: Day One',194,'10 months'),
('Border: Day One',144,'Flicker'),
('Border: Day One',116,'Outro: Cross the line'),
('The Album',203,'How you like that'),
('The Album',212,'Pretty Savage'),
('The Album',240,'Bet You Wanna'),
('The Album',190,'Crazy Over You'),
('The Album',242,'Love to Hate'),
('The Album',210,'You never know'),
('Ice cream',194,'Ice cream'),
('Lovesick girls',200,'Lovesick girls')
